adobe-photoshop/spaces-adapter

- src/ps/ui.js
So we can use it for blitting our canvas, is required by https://github.com/adobe-photoshop/spaces-design/pull/1596
> Add _spaces.window.setOverlayCloaking to ps/ui

- src/lib/selection.js
Adding this so we can get rid of performMenuCommand(1016) in design.
> Add selection API with deselectAll

- src/ps/descriptor.js
Adds the following additional methods to `Descriptor` for efficiently fetching lists of properties from one or more references:
1. `getPropertyRange`, which is like `getPropertiesRange` but for fetching a _single_ property from a range of references.
2. `batchMulitGetProperties` like `getPropertiesRange`, but for fetching a list of properties from an _arbitrary, non-range set_ of references.
3. `multiGetProperties` for fetching a list of properties from a single reference.
4. `multiGetOptionalProperties` for fetching a list of properties from a single reference, in which not all properties need exist on the reference.
All of these calls are functionally identical to other descriptor methods, but each makes at most one call to the Spaces plugin, and hence are faster.
> Additional support for multiGetRef 

- test/spec/low-level-test.js
- Add: _spaces.os.eventKind.MOUSE_MOVE
- Add: _spaces.ps.ui.pointerPropagationMode.ALPHA_PROPAGATE_WITH_NOTIFY
- Add: _spaces.os.notifierKind.EXTERNAL_MOUSE_MOVE
- Add: notifierGroup.DIRECT
- Add: _spaces.window.getBounds()
- Add: _spaces.window.invalidate()
- Add: _spaces.window.changeBounds()
- Add: _spaces.window.setOverlayCloaking()
- Add: _spaces.ps.descriptor.sendDirectMessage()
- Add: _spaces.ps.processQueuedCommands()
- Mod: Made _ref names unique in play(), batchPlay(), get() negative
cases as a debugging aid
- couple of bug fixes, other cleanup
- Add: QUnit.config.testTimeout (5000 ms set as per-test timeout)
> low-level-test updates (playground-dev/...@1028379)

- src/lib/artboard.js
- src/lib/brushes.js
- src/lib/color.js
- src/lib/contentLayer.js
- src/lib/document.js
- src/lib/guide.js
- src/lib/history.js
- src/lib/hitTest.js
- src/lib/layer.js
- src/lib/layerEffect.js
- src/lib/path.js
- src/lib/ruler.js
- src/lib/selection.js
- src/lib/textLayer.js
- src/lib/tool.js
Fixes https://github.com/adobe-photoshop/spaces-design/issues/1638
> Fix filename case for playObject.js requires

- src/ps/ui.js
> Implement UI/startEditWithCurrentModalTool

- src/lib/libraries.js
Subject to change, but they work with the current initial libraries implementation.
> CC Library APIs 0.1

- src/lib/layerEffect.js
- src/lib/libraries.js
- src/lib/textLayer.js
- Adapter functions to save text and layer style thumbnails and export to file
- Adapter functions to apply layer style and text styles to active layers
Hoping these are the last adapter calls we need. @iwehrman Can you review?
> CC Libraries Adapter calls

- docs/SpacesExtension.js
- test/spec/low-level-test.js
SpacesExtension.js @1031280
Add new JS api: _spaces.os.getTempFilename()
low-level-test.js @1031404
Added coverage for the above, and identity test case for another one missed previously.
@iwehrman Please review and merge.
> Adapter updates from Perforce, catnip:23000

- src/lib/layer.js
- src/lib/vectorMask.js
creating a new vector mask adapter lib in order to handle vector mask based actions
> add vector mask based commands to adapter

- src/lib/bounds.js
- src/lib/vectorMask.js
> allow for the addition of vector masks to layers

- src/lib/vectorMask.js
one cleanup that i missed last time around 
assigned to @iwehrman  because he merged the related PR
> delete duplicate export

- src/lib/layer.js
Will be used for graphic sampling, exposes few more Photoshop descriptors to us.
> Add export/replace/relink layer APIs

- src/lib/generator.js
Based on guidance from @isonno
> Adding a generator lib that allows enabling/disablng of generator in photoshop

- src/lib/document.js
Given document ID, guide orientation and position, will put a guide in. Needed for guides work
> Add insertGuide API to document

- src/lib/document.js
We were no longer using this method, but for a certain fix, I am going to be using it again.
> Rewrite setAutoArtboardAttributes to be more refined

- src/lib/preference.js
This is in preparation for fetching the generator plugin port (for export)
> Added a preference lib for getting/setting photoshop custom preferences

- src/ps/descriptor.js
@iwehrman Please review, based on our chat.
At first, I was trying to be clever and wrote: if (object.hasOwnProperty(key) { return a; }), then realized this is identical to last line, `return a`. Then I realized, only way we return b is when a is undefined... so I simplified the function. 
Helps with pasteLayerStyle not failing, since options were not merging.
> Accept existing options in transaction merge

- src/lib/reference.js
Will be used for arrange methods.
> Add next/previous enums to reference wrappers

- src/lib/layerEffect.js
*This PR is compatible with the DS master branch and can be safely merged.*
Added properties conversion for color overlay and stroke, to support updating these two layer effects in DS.
@volfied can you review?
> Support updating color overlay and stroke layer effects.

- src/lib/vectorMask.js
adapter change for the fix for issue https://github.com/adobe-photoshop/spaces-design/issues/2669
> add delete vector mask command

- src/lib/layer.js
Will be used in conjunction with https://github.com/adobe-photoshop/spaces-design/pull/2626 to make setPosition calls emit PS notifications to us.
> Add suppressPlayLevelIncrease to layerLib.translate

- docs/SpacesExtension.js
- test/spec/low-level-test.js
Updates to match for low-level-test: @1048589
@iwehrman Please review and merge.
> Event management-related terminology changes: @1048548

- src/lib/vectorMask.js
part of the fix for issue https://github.com/adobe-photoshop/spaces-design/issues/3029
> add a deselect path Play Object for pen tool

- docs/SpacesExtension.js
- test/spec/low-level-test.js
New constants added to low-level-test
@iwehrman: Please merge when ready
> Update to SpacesExtension.js per right mouse button support constants

- src/lib/hitTest.js
use Core fix for issue https://github.com/adobe-photoshop/spaces-design/issues/1605
> use ignoreEmptyGroup flag on HitTest

- src/lib/libraries.js
This was causing confusion for webpack
> Fix playObject require casing

- bower.json
- package.json
- src/lib/vectorMask.js
These new commands are used by the new vector mask HUD
> add additional path creation command to the vector mask lib

- src/lib/vectorMask.js
Added new path based adapter functions, and bumped the version number
> adding function to create vector mask from shape

- npm-shrinkwrap.json
This adds an npm-shrinkwrap.json file to the repository. This forces `npm install` to only choose specific versions of packages that are known to work in our repository. This will help us guard against packages that don't quite follow semver rules. More information here: https://docs.npmjs.com/cli/shrinkwrap
> Add a shrinkwrap file

- docs/SpacesExtension.js
- test/spec/low-level-test.js
SpacesExtension.js
- Add documentation for new option 'isUserInteractionCommand'
- Changes related to EXTERNAL_MOUSE_MOVE and EXTERNAL_MOUSE_DOWN for
PROPAGATE_BY_ALPHA_AND_NOTIFY events
- Addition of _spaces.os.getMouseLocation()
low-level-test.js
- Converted usages of _spaces.descriptor.play() to batchPlay()
- Added simple ActionDescriptor/play() usage to serve as gestalt/smoke test
- Add _spaces.os.getMouseLocation() test
> SpacesExtension.js @1061853, low-level-test.js @1061610

- docs/SpacesExtension.js
- test/spec/low-level-test.js
- _spaces.feature_flags read-only property added to _spaces
- Testing coverage added to low-level-test.js
> SpacesExtension.js, low-level-test.js @1063165

- docs/SpacesExtension.js
- test/spec/low-level-test.js
_spaces.globalBounds property added to API, coverage added to low-level-test
> _spaces.globalBounds property added to API

- src/lib/owl.js
Adds the getCommandEnabled API to lib.owl
@iwehrman please review.
> Add getCommandEnabled API

- src/os.js
`os.writeFile` and `os.readFile`
> Adds APIs for writing/reading a file

- src/ims.js
- src/index.js
- src/os.js
* ims.getAccessToken
* os.getStandardFolderPath
> Add API: ims.getAccessToken and os.getStandardFolderPath

- README.md
Including how to link spaces-adapter to your project for testing purpose.
https://github.com/adobe-photoshop/spaces-adapter/blob/shao/readme-dev/README.md
> Add development section in the readme

- src/ps.js
Added wrappers for asynchronous readPreferences and writePreferences.
> Use asynchronous read and write preferences API

- src/lib/libraries.js
This PR adds an API `libraries.revealElement` to reveal an element in the Libraries panel.
> Adds API libraries.revealElement

- src/lib/libraries.js
The new descriptor works on no-doc state.
> Use new action descriptor for revealing element

- src/lib/contentLayer.js
- src/lib/libraries.js
- src/lib/vectorMask.js
> Fix eslint errors
