adobe-photoshop/spaces-adapter

- src/ps/descriptor.js
For efficiently getting a list of properties on a range of references.
> Add Descriptor.prototype.getPropertiesRange

- .gitignore
- Gruntfile.js
- package.json
- src/lib/artboard.js
- src/lib/hitTest.js
- src/os.js
- src/ps.js
- src/ps/descriptor.js
- src/ps/ui.js
Just like adobe-photoshop/spaces-design#1643, this adds a `jsdoc` Grunt subtask, and adds it to the default `test` task.
> Validate and generate (but mostly validate) JSDoc

- .gitignore
- Gruntfile.js
- docs/SpacesExtension.js
This adds a copy of the `SpacesExtension.js` file to the repo under `docs/`, and moves the jsdoc to `docs/jsdoc`. @tiburbage is gonna keep this file up-to-date from now on!
> Add SpacesExtension.js

- test/spec/version-test.js
Previously `adapter.version` was a string, but now it's an `{major: number, minor: number, patch: number}` object.
Somebody's gotta tackle the hard problems, folks.
> Fix the version test spec

- src/lib/document.js
- src/lib/layer.js
This is to support export metadata management, but could be used elsewhere in the future.
> Added get/set methods for document and layer extensionData

- src/lib/layerEffect.js
Prevent the **setExtendedLayerEffect** method from sending empty layer effect properties to Photoshop, which will break its layer effect functionality. Instead, it inserts a hidden layer effect properties when the property list is empty, which will delete all layer effects but keep the hidden layer effects in photoshop.
> Bug fix: deleting all layer effects using setExtendedLayerEffect breaks standard Photoshop

- src/lib/layer.js
Adds `layer.setGroupExpansion`, which builds action descriptors to expand or collapse groups.
> Action descriptors to expand/collapse groups.

- src/lib/document.js
- src/lib/layer.js
In my original implementation I took the "references are for suckers" approach, and stuck with what I considered a clean easy-to-consume API that accepts document and layer IDs. Then it turned out more convenient in certain places to provide a docRef because it was already built.  This PR adds the ability for either to be provided.  Is this crazy?  If not, is this something we should generalize?  Maybe we already have in other places and I'm missing it?
> Accept either ref objects or IDs in doc/layer extension data operations

- test/spec/low-level-test.js
Fixed bug in "_spaces.ps.ui.setKeyboardPropagationMode() get/set" test
The only test which should fail now is:
_spaces.os.keyboardFocus: acquire() / release() / isActive() functional
re: https://watsonexp.corp.adobe.com/#bug=4011552
@iwehrman Please review and merge when convenient.
> low-level-test.js @1032036

- src/os.js
Will be used for libraries API, today's Jenkins build has the fix so it works correctly.
> OS.getTempFilename API

- src/lib/contentLayer.js
Used for style copy/paste, to change attributes of a stroke all at once.
> Add setStroke to contentLayer

- src/lib/document.js
Requires playground-dev CL 1037560 (#499) to actually work, will be ignored otherwise so safe to merge.
> Add guide target to insertGuide API

- src/ps/descriptor.js
descriptor.beginTransaction initiates a transaction and returns an object, which is supplied
to different batchPlay calls as the `transaction` key in play options.
At the end of all the action calls, the `descriptor.endTransaction` promise will resolve to play
all the batchPlay objects accumulated underneath that transaction.
Use with caution, all the actions/batchPlay you're calling should be independent of each other,
and not rely on PS model results changing between calls.
- Implemented by @iwehrman, rebased/described by @volfied
> Implement transactions for accumulating batchPlay calls

- src/lib/textLayer.js
WIll help address adobe-photoshop/spaces-design#2255, we store the color in it's own object now.
> Get text color as a single object, not first of an array

- docs/SpacesExtension.js
- test/spec/low-level-test.js
SpacesExtension.js: (@1037966)
- DISPLAY_CONFIGURATION_CHANGED added to _spaces.os.notifierKind
low-level-test.js (@1038504)
- Added helper function getOpenDocumentCount() to enable validating special case issues
where whether a document is open or not affects API behavior
- Added validation logic to "_spaces.os.keyboardFocus: acquire() / release() / isActive() functional"
test to account for an edge case bug (uses new getOpenDocumentCount() helper function)
- Added identity coverage for _spaces.os.notifierKind.DISPLAY_CONFIGURATION_CHANGED
- Improvements to _spaces.os.getTempFilename() test
> Updates from playground-dev/ (Perforce)

- src/lib/document.js
Added `externalPreview` to support cc libraries' open-for-edit feature.
> Add support for external preview settings in document#openDocument

- docs/SpacesExtension.js
- test/spec/low-level-test.js
SpacesExtension.js @1040781
- "synchronous" option key added _spaces.ps.descriptor.play()
- Remove some obsolete definitions
low-level-test.js @1040781
- batchPlay(): tests added: synchronous and asynchronous invoke PS testCommand with echo
- Remove references to some obsoleted definitions
@iwehrman or @mcilroyc : for your review
> Updates from Perforce/playground-dev @1040781

- src/lib/document.js
Since PS changed, this will add guideTarget enum only when we're adding artboard guides. Will help solve https://github.com/adobe-photoshop/spaces-design/issues/2461
> Add guideTarget only for artboard guides

- src/lib/layer.js
Worked on this with Jesper... in PS world, calling "move" for just translating the layers is much much faster than calling "transform", so this is part 1 of a fix for https://github.com/adobe-photoshop/spaces-design/issues/2231.
Part 2 will be getting rid of the "break layers down to all the children" of _getMoveLayerActions... as for translate we don't really need to do it.
> Change translate API to move from transform, because it's faster in PS

- src/lib/document.js
Jesper introduced a new setting to document.open descriptor, which allows us to force file to be added to most recently used. Right now, PS adds opened files to MRU list for ALL files played through external UI, because play level doesn't match. 
I'm providing it "true" to be default because we want most of our opens to be added to MRU unless the file is a library file.
This is one of those PRs with 3 parts, one here, one in spaces-design, and one in perforce.
> Add forceMRU argument to document.open, true unless provided otherwise

- src/lib/layerEffect.js
This opens the full ability of managing all layer effects. This will allow DS to handle unsupported layer effects, and future supported effects (maybe stroke and fill).
@volfied please review.
> Make layerEffect adapter agnostic to shadow types.

- src/lib/tool.js
- src/lib/vectorMask.js
add enterFreeTransformPathMode command, and allow users to set the mode of vector tools to either path or shape. used by https://github.com/adobe-photoshop/spaces-design/pull/1970
> vector mask selection changes

- src/lib/application.js
This adds a `lib/application` module with a `getFontList` PlayObject function. The descriptor uses @isonno's new parameters to control whether the font names are native or English-only.
Partially addresses adobe-photoshop/spaces-design#948.
> Add getFontList PlayObject

- src/lib/document.js
**require dev 772  or staging 1679 to work**
This PR addes option forceMRU (true by default) to `document.closeDocument` so that document saved via the save-before-close dialog will appear in the MRU list. It addresses Design Space issue https://github.com/adobe-photoshop/spaces-design/issues/2866 (no changes required in the DS side).
> Add forceMRU setting to document.close

- src/lib/layer.js
I _think_ PS is interpreting our x/y coordinates in points by default, which is the same as pixels for 72dpi documents. For different resolutions, the translation is not 1:1, so the results are skewed. This forces PS to interpret the coordinate arguments as pixels.
Addresses adobe-photoshop/spaces-design#3121. 
This definitely needs testing. It seemed to solve the problem for artboard swapping, but I haven't yet attempted to test it on other high-level actions which boil down to a "transform" command.
> Specify pixel units in layer transform action descriptor

- src/ps/ui.js
Updated policy action terminology:
1. `ALPHA_PROPAGATE` -> `PROPAGATE_BY_ALPHA`
2. `FOCUS_PROPAGATE` -> `PROPAGATE_BY_FOCUS`
3. `NEVER_PROPAGATE` -> `PROPAGATE_TO_BROWSER`
4. `ALWAYS_PROPAGATE` -> `PROPAGATE_TO_PHOTOSHOP`
> Policy terminology update

- src/lib/index.js
- src/main.js
- src/ps.js
This is a step we need to take for moving to webpack / other module loaders. And it's tied to a big PR that will happen on spaces-design side that is a change we can make independent of all the webpack efforts. 
We've been requiring spaces-adapter directly as a source, and requiring files from it a way project requires it's own files. While this has worked so far... it's not a good practice and prevents us from bundling spaces-adapter seperately. 
This change by itself is safe and will not work current spaces-design.
> Organize adapter code to be bundleable, and fully connected with each other.

- src/main.js
1. Move the plugin-version compatibility check from -adapter to -design
2. In case the check fails, log a warning (error) message instead of throwing a fatal exception.
Step is one is required because the logger is in -design.
> Reduce plugin-compatibility check to a warning

- .jscsrc
- Gruntfile.js
- package.json
- src/lib/application.js
- src/lib/contentLayer.js
- src/lib/document.js
- src/lib/hitTest.js
- src/lib/layer.js
- src/lib/layerEffect.js
- src/lib/photoshopEvent.js
- src/lib/reference.js
- src/lib/ruler.js
- src/lib/textLayer.js
- src/lib/tool.js
- src/lib/unit.js
- src/lib/vectorMask.js
- src/main.js
- src/os.js
- src/playObject.js
- src/ps.js
- src/ps/descriptor.js
- src/ps/ui.js
- src/util.js
- test/specs.js
- test/testrunner.js
This cleans up the linters to generally mirror those in spaces-design:
1. Upgrade `jscs` and copy its `.jscsrc` config over from spaces-design.
2. Add `jsonlint`.
3. Add `lintspaces`.
4. Run linters concurrently with `grunt-concurrent`.
> Linter cleanup

- bower.json
- package.json
- src/ps/descriptor.js
- src/ps/ui.js
We've been using lodash 3.8, but all new libraries use 3.10 and it's good to stay up to date.
However, _.chain().reverse() function mutates the array in place, which causes problems when we call `addLayers`. So this change upgrades lodash and also fixes that issue.
I've also upgraded spaces-adapter version to 0.27.0 so it's not randomly picked up by people.
Other change is making sure a promise returns in the handler so bluebird doesn't complain in it's newer version.
> Upgrade lodash to 3.10

- bower.json
- src/ps/descriptor.js
This is a backward-incompatible upgrade from 2.x to 3.x. Details here: http://bluebirdjs.com/docs/new-in-bluebird-3.html
> Upgrade to bluebird 3.x

- src/lib/application.js
This adds:
1. A `colorStops` enum, which has as values the strings that PS interprets as valid UI color stops;
2. A `setColorStop` function which returns a PlayObject to set the desired color stop.
This adds a new API, so this will necessitate bumping the minor version. As per discussion with @mcilroyc, that will happen only once this is merged to avoid tag shenanigans.
> Color stops

- src/lib/layer.js
This will tell PS to expand/collapse group recursively. This is a fix needed for issue https://github.com/adobe-photoshop/spaces-design/issues/3271.
**Require osx dev >= 932**
> Apply recursive option to setGroupExpansion descriptor.

- src/lib/document.js
This is one of the oldest lib functions we have (one of the first actually), and it doesn't work correctly since we don't provide any parameters for things like drop, width, depth, height when we try to open the files.
So I'm removing it. If, in the future we start saving open parameters of files, it'll be available there. And if PS sees it fit, it will show the Import PDF dialog anyways.
Addresses https://github.com/adobe-photoshop/spaces-design/issues/3253
> Remove ai specific parameterization of documentLib.open

- src/main.js
Will address https://github.com/adobe-photoshop/spaces-design/issues/3398, and when adapter is npm-linked, not show Promise warnings.
> Add Promise.config to disable warnings

- src/lib/document.js
Required for issue #2886
Added it to src/lib/document.js because 'Resolve Fonts' resolves fonts for the entire document.
> Created a Play Object to prompt the resolve font dialog

- src/lib/vectorMask.js
The previous method of copying a vector mask required that you create a temporary path to facilitate the copy. This is no longer required and I've removed the methods that dealt with the temporary path while adding the new copy PlayObject.
> replace support for indirectly moving vector masks with more direct method

- src/ps/ui.js
This is a tiny change that I'm not actually using for anything, but it seems like a good thing to have anyway. The underlying `setOverlayCloaking` function provided by the adapter allows manual cloaking and uncloaking. For the latter, the `list` property of cloaking regions must be empty (to reset cloaking), but our wrapper currently does not support this. This PR just interprets a falsey `area` parameter as the empty list of regions so that this manual uncloaking is possible.
> Support manual un-cloaking

- src/main.js
- src/os.js
This is a new synchronous API that's just added. It directly interfaces with V8 to get the current mouse location relative to the app frame top left. 
Requires playground-dev-mac #972 or later.
> Add getMouseLocation API to OS

- src/lib/application.js
addCopy API will only be available in pg-dev-mac#996 and ahead. The other one exposes already existing globalPreferences set API, allowing us to pass any amount of key/value pairs in.
These will be used in upcoming PRs to address https://github.com/adobe-photoshop/spaces-design/issues/3246 and https://github.com/adobe-photoshop/spaces-design/issues/3543
> Add setGlobalPreference setAddCopy APIs

- package.json
- src/main.js
What it says! Also relaxes the plugin-compatibility check to allow either the previous 2.1.x plugin series or the new play-free 3.0.x series. This will also make it so that, in the future, we can prepare ahead of time for upcoming breaking plugin changes by @jsbache.
Addresses adobe-photoshop/spaces-design#780.
> Use semver to perform plugin-compatibility check

- npm-shrinkwrap.json
What it says! This should have been done in #185, and is currently preventing `npm install` from working as expected.
> Add semver to the shrinkwrap file.

- src/main.js
This changes `COMPATIBLE_PLUGIN_VERSIONS` to be `~3.0.0`, disallowing `2.x` plugins but allowing `3.1.x` plugins.
Over to @mcilroyc for a santiy check.
> Update compatible plugin version spec for 3.1.x series

- src/lib/vectorMask.js
bounds were being passed in as raw numbers and not as units previously
> fix bounds for apply Ellipse Vector mask function

- src/ps/descriptor.js
Empty command will be resolved immediately without making action call to PS.
> Resolve immediately if batchPlay receives empty command.

- src/lib/document.js
- src/lib/owl.js
- src/ps/descriptor.js
1. Add the `getApplicationFrameInfo` OWL action, which allows us to get the bounds of the Photoshop window.
2. Add a default value (`{}`) for the settings argument on `document.openDocument`.
3. Expose a promisified version of `sendDirectMessage` on `Descriptor` instances.
> getApplicationFrameInfo

- src/ps/ui.js
Expose the `performIdentify` command to visually identify rectangular areas in the UI.
> Expose performIdentify

- src/lib/owl.js
Adds a `getViewList` method to construct `PlayObject`s that return a list of the available views.
> Add getViewList

- src/lib/application.js
- src/lib/owl.js
1 - Removes getDocumentArea as now it's an appElement property.
2 - Moves `GetDocumentPresets` and `GetMenuCommands` APIs to lib/application where they belong. They were not OWL APIs.
> Remove getDocumentArea from OWL and move app APIs to app lib

- src/index.js
- src/os.js
- src/playObject.js
- src/ps.js
- src/ps/descriptor.js
- src/ps/ui.js
- src/util.js
With this PR, clients must now instantiate event-emitting adapter classes `Descriptor`, `UI` and `OS` classes. Singletons are no longer exported. This change is motivated by a requirement that `Descriptor` not sign up for notifications of _all_ Photoshop events for performance reasons. Instead, only the subset of notifications required for the application should be forwarded, and this set should be specified by the client at the time of instantiation. To simplify this process, each class now has an associated construction function that sets up event notification and connects it to a returned instance.
This is a breaking API change. Besides requiring clients to create (and share internally) their own instances of these classes, various enums that were previously instance members are now …
> Require client to instantiate adapter classes

- src/ps/descriptor.js
This relaxes the interface of `makeDescriptor` to support lists of event names, or universal event-spec objects like `{ event: "open", universal: true }`.
Requires Mac pdev.1726.
> Support registration of universal descriptor events.

- src/playObject.js
- src/ps/descriptor.js
This PR adds `pause` and `unpause` methods to `Descriptor`  in order to temporarily disable and reenable notifications from Photoshop. @jsbache tells me that this is required for us to be considered good Photoshop citizens, and we certainly consider ourselves as such!
`Descriptor` instances are paused by default, and set no Photoshop notifiers upon construction. Unpausing a `Descriptor` installs its Photoshop notifiers. `makeDescriptor` takes the liberty of calling`unpause` on the returned instance, so this only a breaking change _if you didn't use that API_. (Search does, but I'm not sure about Butler.) Pausing a descriptor uninstalls all of its notifiers, and hence causes it to stop emitting events.
If a client explicitly passes an empty list of events in the options argument, no …
> Pause descriptor events

- src/os.js
`os.getStandardFolderPath` will return an object instead of string after `pgdev 1760`. This PR updates the related JSDoc to reflect the change.
> Update jsdoc for os.getStandardFolderPath

- src/ps/descriptor.js
- src/ps/index.js
- src/ps/messages.js
- src/util/notifierproxy.js
This is a ~~~**REVIEW ONLY**~~~ PR that makes the following changes:
1. Add a `Messages` class that emits direct message events and exposes the `sendDirectMessage` API.
2. Factor out a `NotifierProxy` class that `Descriptor` and `Messages` inherit from to implement the event emitting functionality including pause/unpause.
@volfied: I'd like your feedback on this. I'm testing this now in conjunction with some experimental direct-messages changes along with @dtristram, and so I'm not entirely sure that this works as billed.
> Direct message registration

- npm-shrinkwrap.json
These three dependencies are not listed in the `dependencies` list, which will cause the `extraneous: bluebird@3.3.4 .../spaces-adapter/node_modules/bluebird` error when running the `npm shrinkwrap` command in other projects. 
More details about the `extraneous` error https://github.com/thewoolleyman/npm-shrinkwrap-helper#npm-err-extraneous-
> Remove unused dependencies from npm-shrinkwrap.json

- src/index.js
This removes the Promise config line to solve a problem with couple of our internal projects. It should be the client's responsibility and choice to configure bluebird anyways so this helps with the cleanup.
@iwehrman please review
> Remove promise config line from adapter

- README.md
- package.json
- webpack-prd.config.js
- webpack.config.js
The current release `5.1.0` accidentally bundles the `bluebird@2.11.0`, which could cause error for clients who uses the blurbird's `Cancellation` feature, which is not available in `2.x`. This PR marks `bluebird` as external dependency so that `webpack` command will not bundle the bluebird into the build. 
Other improvements: added `npm run dev` command for development. the command also ignores eslint errors, which will allow the use of `console.info` etc. However, publishing the package will still check for eslint errors.
> Exclude peer dependency when bundling

- package.json
- src/util/notifierproxy.js
This is something we need with NotifierProxies, where events are not subscribed to once, but dynamically change through the life-time of the applications. 
Also fixed a bug with `addListener`, because in it's current state, it was not possible to listen to `"all"` events (workaround was to use `.on`, but that's hacky)
@shaoshing please review.
> Allow notifierProxy to reset listened events

- src/lib/owl.js
Two changes - 
- Added layers panel API, where you can look up the location of the layer cell based on layer name.
- Change tool position API to use toolID (string) instead of toolKey (OSType) since it's easier to parse and is returned in getToolList API already.
@hamburge please review.
> Add getLayersPanelInfo API

- src/lib/owl.js
Adds additional API call for tool info using the `toolKey` of a tool, since `getToolInfo` only accepts the string ID of a tool.
> Add getToolInfoByKey API

- .eslintrc
- src/os.js
**requires pgdev mac >= 2134 win >= 2118**
This PR adds three APIs to accommodate with the new OS External Event Notification Mode added by John F. External events like `externalMouseDown` used to always send to the JS clients regardless of whether they are needed. With the added notification mode, PS will only send the external events that are registered by the clients. (currently these external events are on by default for transition purpose, and they will be turned off by the end of the week). The added APIs are listed below (please check their JSDoc for documentation):
* getExternalEventNotificationMode
* registerExternalEventNotification 
* unregisterExternalEventNotification
> add APIs register/unregisterExternalEventNotification.
